-- ================================================================
-- Seed: school directory → player_profiles
-- Generated 2026-04-22 from the Bears student directory.
--
-- Purpose: pre-links every student's bearsmail.org address so the
-- app skips the signup modal and goes straight to the game on
-- first login from any device.
--
-- How to run: paste into Supabase → SQL Editor → Run.
--
-- Conflicts (two students share the same display name + grade):
--   henry s|9  → Henry Schreck (inserted) vs.
--                 Charles "Henry" Stone  (stonehe29@bearsmail.org)
--                 → Stone must register manually or link post-login
--   bryce s|11 → Bryce Shortt (inserted) vs.
--                 Bryce Smith  (smithbr@bearsmail.org)
--                 → Smith must register manually or link post-login
-- ================================================================

-- ── Grade 9 — Class of 2029 ──────────────────────────────────────
INSERT INTO public.player_profiles
  (player_key, player_name, player_name_key, grade, microsoft_email, source)
VALUES
  ('sophie a|9',       'Sophie A',       'sophie a',       9,  'ali-bubriskiso29@bearsmail.org',  'directory_import'),
  ('king a|9',         'King A',         'king a',         9,  'araujoki29@bearsmail.org',        'directory_import'),
  ('ben a|9',          'Ben A',          'ben a',          9,  'ashleybe29@bearsmail.org',        'directory_import'),
  ('graham b|9',       'Graham B',       'graham b',       9,  'balfourgr29@bearsmail.org',       'directory_import'),
  ('aaron b|9',        'Aaron B',        'aaron b',        9,  'beckaa29@bearsmail.org',          'directory_import'),
  ('morgan b|9',       'Morgan B',       'morgan b',       9,  'bennettmo29@bearsmail.org',       'directory_import'),
  ('finn b|9',         'Finn B',         'finn b',         9,  'bergmannfi29@bearsmail.org',      'directory_import'),
  ('amzie b|9',        'Amzie B',        'amzie b',        9,  'bouldenam29@bearsmail.org',       'directory_import'),
  ('madeline b|9',     'Madeline B',     'madeline b',     9,  'bradnerma29@bearsmail.org',       'directory_import'),
  ('cole b|9',         'Cole B',         'cole b',         9,  'brashierco29@bearsmail.org',      'directory_import'),
  ('krystin b|9',      'Krystin B',      'krystin b',      9,  'bronerkr29@bearsmail.org',        'directory_import'),
  ('natalie b|9',      'Natalie B',      'natalie b',      9,  'brownna29@bearsmail.org',         'directory_import'),
  ('blakely b|9',      'Blakely B',      'blakely b',      9,  'bryanbl29@bearsmail.org',         'directory_import'),
  ('jacob b|9',        'Jacob B',        'jacob b',        9,  'burtja29@bearsmail.org',          'directory_import'),
  ('henry c|9',        'Henry C',        'henry c',        9,  'caldwellhe29@bearsmail.org',      'directory_import'),
  ('kate c|9',         'Kate C',         'kate c',         9,  'caldwellka29@bearsmail.org',      'directory_import'),
  ('robert c|9',       'Robert C',       'robert c',       9,  'campro29@bearsmail.org',          'directory_import'),
  ('chris c|9',        'Chris C',        'chris c',        9,  'cardilloch29@bearsmail.org',      'directory_import'),
  ('byrdie c|9',       'Byrdie C',       'byrdie c',       9,  'chartrandby29@bearsmail.org',     'directory_import'),
  ('fiver c|9',        'Fiver C',        'fiver c',        9,  'cowgillfi29@bearsmail.org',       'directory_import'),
  ('sam c|9',          'Sam C',          'sam c',          9,  'cutlersa29@bearsmail.org',        'directory_import'),
  ('noah d|9',         'Noah D',         'noah d',         9,  'danielno29@bearsmail.org',        'directory_import'),
  ('graham d|9',       'Graham D',       'graham d',       9,  'davisgr29@bearsmail.org',         'directory_import'),
  ('zachary d|9',      'Zachary D',      'zachary d',      9,  'diamondza29@bearsmail.org',       'directory_import'),
  ('ken ken d|9',      'Ken Ken D',      'ken ken d',      9,  'dickenske29@bearsmail.org',       'directory_import'),
  ('ryan d|9',         'Ryan D',         'ryan d',         9,  'dillonry29@bearsmail.org',        'directory_import'),
  ('sawyer d|9',       'Sawyer D',       'sawyer d',       9,  'dillonsa29@bearsmail.org',        'directory_import'),
  ('khloe d|9',        'Khloe D',        'khloe d',        9,  'dowlingkh29@bearsmail.org',       'directory_import'),
  ('hudson d|9',       'Hudson D',       'hudson d',       9,  'downshu29@bearsmail.org',         'directory_import'),
  ('cannon d|9',       'Cannon D',       'cannon d',       9,  'doyleca29@bearsmail.org',         'directory_import'),
  ('addie d|9',        'Addie D',        'addie d',        9,  'duttonad29@bearsmail.org',        'directory_import'),
  ('harrison e|9',     'Harrison E',     'harrison e',     9,  'evansha29@bearsmail.org',         'directory_import'),
  ('mimi f|9',         'Mimi F',         'mimi f',         9,  'fahymi29@bearsmail.org',          'directory_import'),
  ('liam f|9',         'Liam F',         'liam f',         9,  'fayardli29@bearsmail.org',        'directory_import'),
  ('gus f|9',          'Gus F',          'gus f',          9,  'federicogu29@bearsmail.org',      'directory_import'),
  ('banks f|9',        'Banks F',        'banks f',        9,  'ferreroba29@bearsmail.org',       'directory_import'),
  ('hardy f|9',        'Hardy F',        'hardy f',        9,  'forsbergha29@bearsmail.org',      'directory_import'),
  ('ella g|9',         'Ella G',         'ella g',         9,  'garrisonel29@bearsmail.org',      'directory_import'),
  ('matthew g|9',      'Matthew G',      'matthew g',      9,  'georgema29@bearsmail.org',        'directory_import'),
  ('alessandra g|9',   'Alessandra G',   'alessandra g',   9,  'georgieval29@bearsmail.org',      'directory_import'),
  ('yovela g|9',       'Yovela G',       'yovela g',       9,  'gerbieyo29@bearsmail.org',        'directory_import'),
  ('asher g|9',        'Asher G',        'asher g',        9,  'gleesonas29@bearsmail.org',       'directory_import'),
  ('joey g|9',         'Joey G',         'joey g',         9,  'goodejo29@bearsmail.org',         'directory_import'),
  ('caroline g|9',     'Caroline G',     'caroline g',     9,  'grayca29@bearsmail.org',          'directory_import'),
  ('henry g|9',        'Henry G',        'henry g',        9,  'greenehe29@bearsmail.org',        'directory_import'),
  ('nandi g|9',        'Nandi G',        'nandi g',        9,  'griffithna29@bearsmail.org',      'directory_import'),
  ('william h|9',      'William H',      'william h',      9,  'haaswi29@bearsmail.org',          'directory_import'),
  ('ellie h|9',        'Ellie H',        'ellie h',        9,  'harrisel29@bearsmail.org',        'directory_import'),
  ('ridge h|9',        'Ridge H',        'ridge h',        9,  'henningsenri29@bearsmail.org',    'directory_import'),
  ('daniel h|9',       'Daniel H',       'daniel h',       9,  'hillda29@bearsmail.org',          'directory_import'),
  ('temma h|9',        'Temma H',        'temma h',        9,  'hoffenbergte29@bearsmail.org',    'directory_import'),
  ('ollie h|9',        'Ollie H',        'ollie h',        9,  'holdenol29@bearsmail.org',        'directory_import'),
  ('katie h|9',        'Katie H',        'katie h',        9,  'hollandka29@bearsmail.org',       'directory_import'),
  ('colin h|9',        'Colin H',        'colin h',        9,  'horneco29@bearsmail.org',         'directory_import'),
  ('breanna h|9',      'Breanna H',      'breanna h',      9,  'howellbr29@bearsmail.org',        'directory_import'),
  ('ellison h|9',      'Ellison H',      'ellison h',      9,  'hroncichel29@bearsmail.org',      'directory_import'),
  ('parks h|9',        'Parks H',        'parks h',        9,  'hudginspa29@bearsmail.org',       'directory_import'),
  ('joe h|9',          'Joe H',          'joe h',          9,  'huttojo29@bearsmail.org',         'directory_import'),
  ('nicholas i|9',     'Nicholas I',     'nicholas i',     9,  'ivezajni29@bearsmail.org',        'directory_import'),
  ('jake j|9',         'Jake J',         'jake j',         9,  'jansenja29@bearsmail.org',        'directory_import'),
  ('trey j|9',         'Trey J',         'trey j',         9,  'jarrelltr29@bearsmail.org',       'directory_import'),
  ('xavi j|9',         'Xavi J',         'xavi j',         9,  'jogiaxa29@bearsmail.org',         'directory_import'),
  ('jaiden j|9',       'Jaiden J',       'jaiden j',       9,  'johnsonja29@bearsmail.org',       'directory_import'),
  ('lila j|9',         'Lila J',         'lila j',         9,  'jonesli29@bearsmail.org',         'directory_import'),
  ('samantha j|9',     'Samantha J',     'samantha j',     9,  'jordansa29@bearsmail.org',        'directory_import'),
  ('kaleb k|9',        'Kaleb K',        'kaleb k',        9,  'kaplanka29@bearsmail.org',        'directory_import'),
  ('penny k|9',        'Penny K',        'penny k',        9,  'kentpe29@bearsmail.org',          'directory_import'),
  ('melina k|9',       'Melina K',       'melina k',       9,  'khademime29@bearsmail.org',       'directory_import'),
  ('bates l|9',        'Bates L',        'bates l',        9,  'laughlinba29@bearsmail.org',      'directory_import'),
  ('miller l|9',       'Miller L',       'miller l',       9,  'laughlinmi29@bearsmail.org',      'directory_import'),
  ('jack l|9',         'Jack L',         'jack l',         9,  'lewisja29@bearsmail.org',         'directory_import'),
  ('eve m|9',          'Eve M',          'eve m',          9,  'marksev29@bearsmail.org',         'directory_import'),
  ('harrison m|9',     'Harrison M',     'harrison m',     9,  'mcbrayerha29@bearsmail.org',      'directory_import'),
  ('gracie m|9',       'Gracie M',       'gracie m',       9,  'mccordgr29@bearsmail.org',        'directory_import'),
  ('callan m|9',       'Callan M',       'callan m',       9,  'mckayca29@bearsmail.org',         'directory_import'),
  ('sophie m|9',       'Sophie M',       'sophie m',       9,  'mckayso29@bearsmail.org',         'directory_import'),
  ('finley m|9',       'Finley M',       'finley m',       9,  'metznerfi29@bearsmail.org',       'directory_import'),
  ('sanders m|9',      'Sanders M',      'sanders m',       9,  'mitchenersa29@bearsmail.org',     'directory_import'),
  ('hannah m|9',       'Hannah M',       'hannah m',       9,  'morrisha29@bearsmail.org',        'directory_import'),
  ('fernando n|9',     'Fernando N',     'fernando n',     9,  'notariorochafe29@bearsmail.org',  'directory_import'),
  ('hudson n|9',       'Hudson N',       'hudson n',       9,  'nowakhu29@bearsmail.org',         'directory_import'),
  ('aidan o|9',        'Aidan O',        'aidan o',        9,  'oconnorai29@bearsmail.org',       'directory_import'),
  ('amariah o|9',      'Amariah O',      'amariah o',      9,  'ogeneam29@bearsmail.org',         'directory_import'),
  ('mark o|9',         'Mark O',         'mark o',         9,  'orzhekhovskiyma29@bearsmail.org', 'directory_import'),
  ('abe o|9',          'Abe O',          'abe o',          9,  'osmanab29@bearsmail.org',         'directory_import'),
  ('chelsea p|9',      'Chelsea P',      'chelsea p',      9,  'pachecoch29@bearsmail.org',       'directory_import'),
  ('ireland p|9',      'Ireland P',      'ireland p',      9,  'padgettir29@bearsmail.org',       'directory_import'),
  ('caden p|9',        'Caden P',        'caden p',        9,  'pageca29@bearsmail.org',          'directory_import'),
  ('parker p|9',       'Parker P',       'parker p',       9,  'panospa29@bearsmail.org',         'directory_import'),
  ('melanie p|9',      'Melanie P',      'melanie p',      9,  'parrisme29@bearsmail.org',        'directory_import'),
  ('auldyn p|9',       'Auldyn P',       'auldyn p',       9,  'patakau29@bearsmail.org',         'directory_import'),
  ('luke p|9',         'Luke P',         'luke p',         9,  'pattonlu29@bearsmail.org',        'directory_import'),
  ('camille p|9',      'Camille P',      'camille p',      9,  'paulhusca29@bearsmail.org',       'directory_import'),
  ('ryan p|9',         'Ryan P',         'ryan p',         9,  'peckhamry29@bearsmail.org',       'directory_import'),
  ('christian p|9',    'Christian P',    'christian p',    9,  'petersch29@bearsmail.org',        'directory_import'),
  ('isabelle p|9',     'Isabelle P',     'isabelle p',     9,  'petersis29@bearsmail.org',        'directory_import'),
  ('kennedy p|9',      'Kennedy P',      'kennedy p',      9,  'peterske29@bearsmail.org',        'directory_import'),
  ('alice p|9',        'Alice P',        'alice p',        9,  'poeal29@bearsmail.org',           'directory_import'),
  ('truman r|9',       'Truman R',       'truman r',       9,  'reedtr29@bearsmail.org',          'directory_import'),
  ('jack r|9',         'Jack R',         'jack r',         9,  'robinsonja29@bearsmail.org',      'directory_import'),
  ('ava r|9',          'Ava R',          'ava r',          9,  'rollinsav29@bearsmail.org',       'directory_import'),
  ('haiden r|9',       'Haiden R',       'haiden r',       9,  'rossha29@bearsmail.org',          'directory_import'),
  ('mack r|9',         'Mack R',         'mack r',         9,  'russellma29@bearsmail.org',       'directory_import'),
  -- henry s|9 → Schreck inserted; Stone (stonehe29@bearsmail.org) must register manually
  ('henry s|9',        'Henry S',        'henry s',        9,  'schreckhe29@bearsmail.org',       'directory_import'),
  ('bobby s|9',        'Bobby S',        'bobby s',        9,  'shapirobo29@bearsmail.org',       'directory_import'),
  ('liam s|9',         'Liam S',         'liam s',         9,  'silhanli29@bearsmail.org',        'directory_import'),
  ('aria s|9',         'Aria S',         'aria s',         9,  'simmonsar29@bearsmail.org',       'directory_import'),
  ('xavier s|9',       'Xavier S',       'xavier s',       9,  'smileyxa29@bearsmail.org',        'directory_import'),
  ('adrianna s|9',     'Adrianna S',     'adrianna s',     9,  'smithad29@bearsmail.org',         'directory_import'),
  ('parker s|9',       'Parker S',       'parker s',       9,  'smithpa29@bearsmail.org',         'directory_import'),
  ('matthew s|9',      'Matthew S',      'matthew s',      9,  'somersallma29@bearsmail.org',     'directory_import'),
  ('cole s|9',         'Cole S',         'cole s',         9,  'spragueco29@bearsmail.org',       'directory_import'),
  ('hudson s|9',       'Hudson S',       'hudson s',       9,  'stephenshu29@bearsmail.org',      'directory_import'),
  ('thomas s|9',       'Thomas S',       'thomas s',       9,  'stottsth29@bearsmail.org',        'directory_import'),
  ('rylee s|9',        'Rylee S',        'rylee s',        9,  'swainry29@bearsmail.org',         'directory_import'),
  ('beckett t|9',      'Beckett T',      'beckett t',      9,  'talbertbe29@bearsmail.org',       'directory_import'),
  ('harry t|9',        'Harry T',        'harry t',        9,  'thompsonha29@bearsmail.org',      'directory_import'),
  ('liza t|9',         'Liza T',         'liza t',         9,  'tomilovli29@bearsmail.org',       'directory_import'),
  ('hattie t|9',       'Hattie T',       'hattie t',       9,  'troupha29@bearsmail.org',         'directory_import'),
  ('bella w|9',        'Bella W',        'bella w',        9,  'weinsteinbe29@bearsmail.org',     'directory_import'),
  ('william w|9',      'William W',      'william w',      9,  'whittywi29@bearsmail.org',        'directory_import'),
  ('sydney w|9',       'Sydney W',       'sydney w',       9,  'williamssy29@bearsmail.org',      'directory_import'),
  ('mary drew w|9',    'Mary Drew W',    'mary drew w',    9,  'wisema29@bearsmail.org',          'directory_import')
ON CONFLICT (player_key) DO UPDATE SET
  microsoft_email = EXCLUDED.microsoft_email,
  updated_at      = now()
WHERE player_profiles.microsoft_email IS NULL;

-- ── Grade 10 — Class of 2028 ─────────────────────────────────────
INSERT INTO public.player_profiles
  (player_key, player_name, player_name_key, grade, microsoft_email, source)
VALUES
  ('andrew a|10',       'Andrew A',       'andrew a',       10, 'altmanan@bearsmail.org',        'directory_import'),
  ('madison a|10',      'Madison A',      'madison a',      10, 'angellma@bearsmail.org',        'directory_import'),
  ('brayden b|10',      'Brayden B',      'brayden b',      10, 'baileybr@bearsmail.org',        'directory_import'),
  ('xavier b|10',       'Xavier B',       'xavier b',       10, 'bergmannxa28@bearsmail.org',    'directory_import'),
  ('quinn b|10',        'Quinn B',        'quinn b',        10, 'bestqu28@bearsmail.org',         'directory_import'),
  ('madeline b|10',     'Madeline B',     'madeline b',     10, 'billianma@bearsmail.org',       'directory_import'),
  ('strickland b|10',   'Strickland B',   'strickland b',   10, 'bloomstonst@bearsmail.org',     'directory_import'),
  ('ingrid b|10',       'Ingrid B',       'ingrid b',       10, 'bongersin@bearsmail.org',       'directory_import'),
  ('jackson b|10',      'Jackson B',      'jackson b',      10, 'brownja@bearsmail.org',         'directory_import'),
  ('karissa b|10',      'Karissa B',      'karissa b',      10, 'brownka28@bearsmail.org',       'directory_import'),
  ('bennett b|10',      'Bennett B',      'bennett b',      10, 'burroughsbe@bearsmail.org',     'directory_import'),
  ('nicholas b|10',     'Nicholas B',     'nicholas b',     10, 'buschni@bearsmail.org',         'directory_import'),
  ('will b|10',         'Will B',         'will b',         10, 'bykatwi28@bearsmail.org',       'directory_import'),
  ('cole c|10',         'Cole C',         'cole c',         10, 'campbellco@bearsmail.org',      'directory_import'),
  ('bailey c|10',       'Bailey C',       'bailey c',       10, 'carperba@bearsmail.org',        'directory_import'),
  ('fisher c|10',       'Fisher C',       'fisher c',       10, 'catonefi28@bearsmail.org',      'directory_import'),
  ('ronan c|10',        'Ronan C',        'ronan c',        10, 'chauhanro@bearsmail.org',       'directory_import'),
  ('bentley c|10',      'Bentley C',      'bentley c',      10, 'childersbe28@bearsmail.org',    'directory_import'),
  ('lucas c|10',        'Lucas C',        'lucas c',        10, 'chonglu@bearsmail.org',         'directory_import'),
  ('eden c|10',         'Eden C',         'eden c',         10, 'coiled@bearsmail.org',          'directory_import'),
  ('madison c|10',      'Madison C',      'madison c',      10, 'coleyma@bearsmail.org',         'directory_import'),
  ('bree c|10',         'Bree C',         'bree c',         10, 'collinsbr28@bearsmail.org',     'directory_import'),
  ('eva c|10',          'Eva C',          'eva c',          10, 'connorsev@bearsmail.org',       'directory_import'),
  ('mackenzie c|10',    'Mackenzie C',    'mackenzie c',    10, 'cromartiema28@bearsmail.org',   'directory_import'),
  ('liam d|10',         'Liam D',         'liam d',         10, 'delaneyli28@bearsmail.org',     'directory_import'),
  ('lane d|10',         'Lane D',         'lane d',         10, 'derisola@bearsmail.org',        'directory_import'),
  ('hudson d|10',       'Hudson D',       'hudson d',       10, 'dipintocamiahu@bearsmail.org',  'directory_import'),
  ('thomas d|10',       'Thomas D',       'thomas d',       10, 'doughertyth@bearsmail.org',     'directory_import'),
  ('ryan d|10',         'Ryan D',         'ryan d',         10, 'dunhamry@bearsmail.org',        'directory_import'),
  ('ellison e|10',      'Ellison E',      'ellison e',      10, 'eilyel28@bearsmail.org',        'directory_import'),
  ('garrett e|10',      'Garrett E',      'garrett e',      10, 'evansga@bearsmail.org',         'directory_import'),
  ('emily g|10',        'Emily G',        'emily g',        10, 'gainerem28@bearsmail.org',      'directory_import'),
  ('sam g|10',          'Sam G',          'sam g',          10, 'gallantsa28@bearsmail.org',     'directory_import'),
  ('jackie g|10',       'Jackie G',       'jackie g',       10, 'garciaja28@bearsmail.org',      'directory_import'),
  ('elizabeth g|10',    'Elizabeth G',    'elizabeth g',    10, 'greenel@bearsmail.org',         'directory_import'),
  ('lydia g|10',        'Lydia G',        'lydia g',        10, 'gregoryly@bearsmail.org',       'directory_import'),
  ('davis g|10',        'Davis G',        'davis g',        10, 'griffinda@bearsmail.org',       'directory_import'),
  ('will g|10',         'Will G',         'will g',         10, 'ginsbergwi28@bearsmail.org',    'directory_import'),
  ('lila g|10',         'Lila G',         'lila g',         10, 'goodmonli@bearsmail.org',       'directory_import'),
  ('teddy h|10',        'Teddy H',        'teddy h',        10, 'hawkinste28@bearsmail.org',     'directory_import'),
  ('violet h|10',       'Violet H',       'violet h',       10, 'hawkinsvi28@bearsmail.org',     'directory_import'),
  ('carson h|10',       'Carson H',       'carson h',       10, 'hollierca28@bearsmail.org',     'directory_import'),
  ('samantha h|10',     'Samantha H',     'samantha h',     10, 'huntersa@bearsmail.org',        'directory_import'),
  ('sky i|10',          'Sky I',          'sky i',          10, 'idlettsk28@bearsmail.org',      'directory_import'),
  ('bella i|10',        'Bella I',        'bella i',        10, 'ivezajbe@bearsmail.org',        'directory_import'),
  ('sloane j|10',       'Sloane J',       'sloane j',       10, 'jenkinssl@bearsmail.org',       'directory_import'),
  ('violet j|10',       'Violet J',       'violet j',       10, 'jonesvi@bearsmail.org',         'directory_import'),
  ('martin j|10',       'Martin J',       'martin j',       10, 'josema28@bearsmail.org',        'directory_import'),
  ('landen k|10',       'Landen K',       'landen k',       10, 'kloppla28@bearsmail.org',       'directory_import'),
  ('cooper k|10',       'Cooper K',       'cooper k',       10, 'knowlesco@bearsmail.org',       'directory_import'),
  ('cathryn-rose k|10', 'Cathryn-Rose K', 'cathryn-rose k', 10, 'kolbca28@bearsmail.org',        'directory_import'),
  ('mary-grace k|10',   'Mary-Grace K',   'mary-grace k',   10, 'kolbma28@bearsmail.org',        'directory_import'),
  ('cristiano l|10',    'Cristiano L',    'cristiano l',    10, 'laioscr@bearsmail.org',         'directory_import'),
  ('addison l|10',      'Addison L',      'addison l',      10, 'leead@bearsmail.org',           'directory_import'),
  ('ellison l|10',      'Ellison L',      'ellison l',      10, 'losinel28@bearsmail.org',       'directory_import'),
  ('charlie m|10',      'Charlie M',      'charlie m',      10, 'macech@bearsmail.org',          'directory_import'),
  ('peighton m|10',     'Peighton M',     'peighton m',     10, 'mallaype@bearsmail.org',        'directory_import'),
  ('bella m|10',        'Bella M',        'bella m',        10, 'mattoxbe28@bearsmail.org',      'directory_import'),
  ('jaden m|10',        'Jaden M',        'jaden m',        10, 'mcculloughja28@bearsmail.org',  'directory_import'),
  ('mary brooks m|10',  'Mary Brooks M',  'mary brooks m',  10, 'mccrystalma@bearsmail.org',     'directory_import'),
  ('julia-pun m|10',    'Julia-Pun M',    'julia-pun m',    10, 'mcgheeju@bearsmail.org',        'directory_import'),
  ('addison m|10',      'Addison M',      'addison m',      10, 'mcmillenad@bearsmail.org',      'directory_import'),
  ('crosby m|10',       'Crosby M',       'crosby m',       10, 'mcmillencr@bearsmail.org',      'directory_import'),
  ('ryan m|10',         'Ryan M',         'ryan m',         10, 'mckayry@bearsmail.org',         'directory_import'),
  ('gemma m|10',        'Gemma M',        'gemma m',        10, 'mellonge28@bearsmail.org',      'directory_import'),
  ('sophia m|10',       'Sophia M',       'sophia m',       10, 'meszarosso@bearsmail.org',      'directory_import'),
  ('townsend m|10',     'Townsend M',     'townsend m',     10, 'mooneyto@bearsmail.org',        'directory_import'),
  ('belle m|10',        'Belle M',        'belle m',        10, 'moorebe28@bearsmail.org',       'directory_import'),
  ('alexa m|10',        'Alexa M',        'alexa m',        10, 'mooreheadal@bearsmail.org',     'directory_import'),
  ('merrick m|10',      'Merrick M',      'merrick m',      10, 'mooreheadme@bearsmail.org',     'directory_import'),
  ('amaya m|10',        'Amaya M',        'amaya m',        10, 'morrisam28@bearsmail.org',      'directory_import'),
  ('jackson m|10',      'Jackson M',      'jackson m',      10, 'mullinsja28@bearsmail.org',     'directory_import'),
  ('landon m|10',       'Landon M',       'landon m',       10, 'murrayla@bearsmail.org',        'directory_import'),
  ('loriel m|10',       'Loriel M',       'loriel m',       10, 'murraylo28@bearsmail.org',      'directory_import'),
  ('connor m|10',       'Connor M',       'connor m',       10, 'mutzco28@bearsmail.org',        'directory_import'),
  ('bobby n|10',        'Bobby N',        'bobby n',        10, 'nardellibo28@bearsmail.org',    'directory_import'),
  ('ayden n|10',        'Ayden N',        'ayden n',        10, 'nidaay@bearsmail.org',          'directory_import'),
  ('will o|10',         'Will O',         'will o',         10, 'oconnorwi28@bearsmail.org',     'directory_import'),
  ('maia o|10',         'Maia O',         'maia o',         10, 'olearyma28@bearsmail.org',      'directory_import'),
  ('emme o|10',         'Emme O',         'emme o',         10, 'oneilem@bearsmail.org',         'directory_import'),
  ('jonah o|10',        'Jonah O',        'jonah o',        10, 'osbornejo28@bearsmail.org',     'directory_import'),
  ('caroline p|10',     'Caroline P',     'caroline p',     10, 'paulhusca@bearsmail.org',       'directory_import'),
  ('lucas p|10',        'Lucas P',        'lucas p',        10, 'pecklu@bearsmail.org',          'directory_import'),
  ('lucy p|10',         'Lucy P',         'lucy p',         10, 'petersonlu@bearsmail.org',      'directory_import'),
  ('turner p|10',       'Turner P',       'turner p',       10, 'petersontu28@bearsmail.org',    'directory_import'),
  ('cole p|10',         'Cole P',         'cole p',         10, 'prattco28@bearsmail.org',       'directory_import'),
  ('grant q|10',        'Grant Q',        'grant q',        10, 'quilesgr28@bearsmail.org',      'directory_import'),
  ('ava r|10',          'Ava R',          'ava r',          10, 'ruinenav28@bearsmail.org',      'directory_import'),
  ('mia s|10',          'Mia S',          'mia s',          10, 'sguilaromi28@bearsmail.org',    'directory_import'),
  ('olivia s|10',       'Olivia S',       'olivia s',       10, 'sharperol28@bearsmail.org',     'directory_import'),
  ('kaylee s|10',       'Kaylee S',       'kaylee s',       10, 'sheatska28@bearsmail.org',      'directory_import'),
  ('riley s|10',        'Riley S',        'riley s',        10, 'shepherdri28@bearsmail.org',    'directory_import'),
  ('daniel s|10',       'Daniel S',       'daniel s',       10, 'siddiquida@bearsmail.org',      'directory_import'),
  ('logan s|10',        'Logan S',        'logan s',        10, 'skaggslo@bearsmail.org',        'directory_import'),
  ('cole s|10',         'Cole S',         'cole s',         10, 'smithco@bearsmail.org',         'directory_import'),
  ('jude s|10',         'Jude S',         'jude s',         10, 'smithju28@bearsmail.org',       'directory_import'),
  ('sarah s|10',        'Sarah S',        'sarah s',        10, 'snyders@bearsmail.org',         'directory_import'),
  ('maddie s|10',       'Maddie S',       'maddie s',       10, 'spectorma@bearsmail.org',       'directory_import'),
  ('molly s|10',        'Molly S',        'molly s',        10, 'spectormo@bearsmail.org',       'directory_import'),
  ('bobby s|10',        'Bobby S',        'bobby s',        10, 'spencerbo28@bearsmail.org',     'directory_import'),
  ('aspen s|10',        'Aspen S',        'aspen s',        10, 'starkas28@bearsmail.org',       'directory_import'),
  ('jack s|10',         'Jack S',         'jack s',         10, 'stoneja28@bearsmail.org',       'directory_import'),
  ('shane s|10',        'Shane S',        'shane s',        10, 'strobridgesh@bearsmail.org',    'directory_import'),
  ('miller t|10',       'Miller T',       'miller t',       10, 'tablermi@bearsmail.org',        'directory_import'),
  ('lucas t|10',        'Lucas T',        'lucas t',        10, 'tiliakoslu@bearsmail.org',      'directory_import'),
  ('aubrey t|10',       'Aubrey T',       'aubrey t',       10, 'towsonau28@bearsmail.org',      'directory_import'),
  ('bryson t|10',       'Bryson T',       'bryson t',       10, 'tyebr28@bearsmail.org',         'directory_import'),
  ('allison v|10',      'Allison V',      'allison v',      10, 'varelaal28@bearsmail.org',      'directory_import'),
  ('caroline w|10',     'Caroline W',     'caroline w',     10, 'wakelyca@bearsmail.org',        'directory_import'),
  ('logan w|10',        'Logan W',        'logan w',        10, 'walkerlo@bearsmail.org',        'directory_import'),
  ('makenzie w|10',     'Makenzie W',     'makenzie w',     10, 'weaverma28@bearsmail.org',      'directory_import'),
  ('daniel w|10',       'Daniel W',       'daniel w',       10, 'weaverda@bearsmail.org',        'directory_import'),
  ('adair w|10',        'Adair W',        'adair w',        10, 'weeksad@bearsmail.org',         'directory_import'),
  ('wilkins w|10',      'Wilkins W',      'wilkins w',      10, 'wileywi28@bearsmail.org',       'directory_import'),
  ('treasure w|10',     'Treasure W',     'treasure w',     10, 'williamstr28@bearsmail.org',    'directory_import'),
  ('ashley w|10',       'Ashley W',       'ashley w',       10, 'wilsonas28@bearsmail.org',      'directory_import'),
  ('sam w|10',          'Sam W',          'sam w',          10, 'wimberlysa28@bearsmail.org',    'directory_import'),
  ('ryan w|10',         'Ryan W',         'ryan w',         10, 'woodsry@bearsmail.org',         'directory_import'),
  ('gabby t|10',        'Gabby T',        'gabby t',        10, 'tubajikaga28@bearsmail.org',    'directory_import'),
  ('divya y|10',        'Divya Y',        'divya y',        10, 'yogarajdi28@bearsmail.org',     'directory_import')
ON CONFLICT (player_key) DO UPDATE SET
  microsoft_email = EXCLUDED.microsoft_email,
  updated_at      = now()
WHERE player_profiles.microsoft_email IS NULL;

-- ── Grade 11 — Class of 2027 ─────────────────────────────────────
INSERT INTO public.player_profiles
  (player_key, player_name, player_name_key, grade, microsoft_email, source)
VALUES
  ('emerson a|11',     'Emerson A',     'emerson a',     11, 'argyleem27@bearsmail.org',       'directory_import'),
  ('william a|11',     'William A',     'william a',     11, 'ashleywi27@bearsmail.org',       'directory_import'),
  ('mitchell b|11',    'Mitchell B',    'mitchell b',    11, 'bainbridgemi@bearsmail.org',     'directory_import'),
  ('rhodes b|11',      'Rhodes B',      'rhodes b',      11, 'baylissrh27@bearsmail.org',      'directory_import'),
  ('daniel b|11',      'Daniel B',      'daniel b',      11, 'bealleda@bearsmail.org',         'directory_import'),
  ('brooke b|11',      'Brooke B',      'brooke b',      11, 'benedictbr@bearsmail.org',       'directory_import'),
  ('avery b|11',       'Avery B',       'avery b',       11, 'bennettav@bearsmail.org',        'directory_import'),
  ('cesar b|11',       'Cesar B',       'cesar b',       11, 'buendiace27@bearsmail.org',      'directory_import'),
  ('gavin c|11',       'Gavin C',       'gavin c',       11, 'camposga@bearsmail.org',         'directory_import'),
  ('arden c|11',       'Arden C',       'arden c',       11, 'carabajalar@bearsmail.org',      'directory_import'),
  ('davis c|11',       'Davis C',       'davis c',       11, 'carlisleda@bearsmail.org',       'directory_import'),
  ('margot c|11',      'Margot C',      'margot c',      11, 'carrierema@bearsmail.org',       'directory_import'),
  ('hotoniel c|11',    'Hotoniel C',    'hotoniel c',    11, 'chajho27@bearsmail.org',         'directory_import'),
  ('jack c|11',        'Jack C',        'jack c',        11, 'chaloupekja27@bearsmail.org',    'directory_import'),
  ('sam c|11',         'Sam C',         'sam c',         11, 'chasteensa27@bearsmail.org',     'directory_import'),
  ('robby c|11',       'Robby C',       'robby c',       11, 'chiaffredoro@bearsmail.org',     'directory_import'),
  ('margaret c|11',    'Margaret C',    'margaret c',    11, 'colema27@bearsmail.org',         'directory_import'),
  ('christina c|11',   'Christina C',   'christina c',   11, 'costaridesch27@bearsmail.org',   'directory_import'),
  ('emmy c|11',        'Emmy C',        'emmy c',        11, 'courtsem@bearsmail.org',         'directory_import'),
  ('felipe c|11',      'Felipe C',      'felipe c',      11, 'cruzfe27@bearsmail.org',         'directory_import'),
  ('florencia c|11',   'Florencia C',   'florencia c',   11, 'cruzfl27@bearsmail.org',         'directory_import'),
  ('grey c|11',        'Grey C',        'grey c',        11, 'cullensgr@bearsmail.org',        'directory_import'),
  ('claire c|11',      'Claire C',      'claire c',      11, 'cummingsc@bearsmail.org',        'directory_import'),
  ('caroline d|11',    'Caroline D',    'caroline d',    11, 'davisca@bearsmail.org',          'directory_import'),
  ('hailey d|11',      'Hailey D',      'hailey d',      11, 'davisha27@bearsmail.org',        'directory_import'),
  ('ryan d|11',        'Ryan D',        'ryan d',        11, 'deguirery27@bearsmail.org',      'directory_import'),
  ('jackson d|11',     'Jackson D',     'jackson d',     11, 'dillonja@bearsmail.org',         'directory_import'),
  ('aj d|11',          'AJ D',          'aj d',          11, 'donnellyaj@bearsmail.org',       'directory_import'),
  ('amara d|11',       'Amara D',       'amara d',       11, 'donnellyam27@bearsmail.org',     'directory_import'),
  ('jon miller d|11',  'Jon Miller D',  'jon miller d',  11, 'doughtiejo@bearsmail.org',       'directory_import'),
  ('anaya e|11',       'Anaya E',       'anaya e',       11, 'ellisonan27@bearsmail.org',      'directory_import'),
  ('patrick f|11',     'Patrick F',     'patrick f',     11, 'feaginpa27@bearsmail.org',       'directory_import'),
  ('juliana f|11',     'Juliana F',     'juliana f',     11, 'federicoju27@bearsmail.org',     'directory_import'),
  ('nicholas f|11',    'Nicholas F',    'nicholas f',    11, 'feinbergni@bearsmail.org',       'directory_import'),
  ('finn f|11',        'Finn F',        'finn f',        11, 'ferrerofi@bearsmail.org',        'directory_import'),
  ('connor f|11',      'Connor F',      'connor f',      11, 'forgeyco27@bearsmail.org',       'directory_import'),
  ('andrew f|11',      'Andrew F',      'andrew f',      11, 'forgionean27@bearsmail.org',     'directory_import'),
  ('ella f|11',        'Ella F',        'ella f',        11, 'fowlerel@bearsmail.org',         'directory_import'),
  ('emma f|11',        'Emma F',        'emma f',        11, 'frankem@bearsmail.org',          'directory_import'),
  ('kate f|11',        'Kate F',        'kate f',        11, 'frankka@bearsmail.org',          'directory_import'),
  ('mary f|11',        'Mary F',        'mary f',        11, 'fullerma@bearsmail.org',         'directory_import'),
  ('brendan g|11',     'Brendan G',     'brendan g',     11, 'ganucheaubr27@bearsmail.org',   'directory_import'),
  ('joselyn g|11',     'Joselyn G',     'joselyn g',     11, 'garciajo27@bearsmail.org',       'directory_import'),
  ('mateo g|11',       'Mateo G',       'mateo g',       11, 'garciama27@bearsmail.org',       'directory_import'),
  ('eliana g|11',      'Eliana G',      'eliana g',      11, 'gerbiel@bearsmail.org',          'directory_import'),
  ('graham g|11',      'Graham G',      'graham g',      11, 'goddardgr@bearsmail.org',        'directory_import'),
  ('nora g|11',        'Nora G',        'nora g',        11, 'godfreyno@bearsmail.org',        'directory_import'),
  ('will g|11',        'Will G',        'will g',        11, 'goldbergwi@bearsmail.org',       'directory_import'),
  ('jackson g|11',     'Jackson G',     'jackson g',     11, 'greeneja27@bearsmail.org',       'directory_import'),
  ('tuck g|11',        'Tuck G',        'tuck g',        11, 'greenetu@bearsmail.org',         'directory_import'),
  ('amaree g|11',      'Amaree G',      'amaree g',      11, 'griffinam27@bearsmail.org',      'directory_import'),
  ('phillip g|11',     'Phillip G',     'phillip g',     11, 'griffinph27@bearsmail.org',      'directory_import'),
  ('maxx g|11',        'Maxx G',        'maxx g',        11, 'grooverma@bearsmail.org',        'directory_import'),
  ('betsy g|11',       'Betsy G',       'betsy g',       11, 'guybe@bearsmail.org',            'directory_import'),
  ('sophie h|11',      'Sophie H',      'sophie h',      11, 'harkeyso27@bearsmail.org',       'directory_import'),
  ('cole h|11',        'Cole H',        'cole h',        11, 'hatfieldco27@bearsmail.org',     'directory_import'),
  ('grant h|11',       'Grant H',       'grant h',       11, 'henngr@bearsmail.org',           'directory_import'),
  ('alexa h|11',       'Alexa H',       'alexa h',       11, 'henningsenal@bearsmail.org',     'directory_import'),
  ('sammy h|11',       'Sammy H',       'sammy h',       11, 'herdsa27@bearsmail.org',         'directory_import'),
  ('sidney-ann h|11',  'Sidney-Ann H',  'sidney-ann h',  11, 'hickmansi27@bearsmail.org',      'directory_import'),
  ('blair h|11',       'Blair H',       'blair h',       11, 'huberbl@bearsmail.org',          'directory_import'),
  ('evelyn grace h|11','Evelyn Grace H','evelyn grace h', 11, 'hydeev27@bearsmail.org',         'directory_import'),
  ('gracie i|11',      'Gracie I',      'gracie i',      11, 'igoegr27@bearsmail.org',         'directory_import'),
  ('ayokunle i|11',    'Ayokunle I',    'ayokunle i',    11, 'iyandaay27@bearsmail.org',       'directory_import'),
  ('meriwether j|11',  'Meriwether J',  'meriwether j',  11, 'jaaxme27@bearsmail.org',         'directory_import'),
  ('paige j|11',       'Paige J',       'paige j',       11, 'jacquinpa@bearsmail.org',        'directory_import'),
  ('ria j|11',         'Ria J',         'ria j',         11, 'jainri27@bearsmail.org',         'directory_import'),
  ('amelia j|11',      'Amelia J',      'amelia j',      11, 'johnsonam@bearsmail.org',        'directory_import'),
  ('hannah j|11',      'Hannah J',      'hannah j',      11, 'johnsonha@bearsmail.org',        'directory_import'),
  ('katlynn j|11',     'Katlynn J',     'katlynn j',     11, 'johnsonka27@bearsmail.org',      'directory_import'),
  ('teagan j|11',      'Teagan J',      'teagan j',      11, 'johnsonte@bearsmail.org',        'directory_import'),
  ('beatrice j|11',    'Beatrice J',    'beatrice j',    11, 'jonesbe27@bearsmail.org',        'directory_import'),
  ('caroline k|11',    'Caroline K',    'caroline k',    11, 'katzca27@bearsmail.org',         'directory_import'),
  ('sarah k|11',       'Sarah K',       'sarah k',       11, 'kirkpatricksa@bearsmail.org',    'directory_import'),
  ('vance l|11',       'Vance L',       'vance l',       11, 'laneva27@bearsmail.org',         'directory_import'),
  ('hunter l|11',      'Hunter L',      'hunter l',      11, 'laughlinhu@bearsmail.org',       'directory_import'),
  ('brad l|11',        'Brad L',        'brad l',        11, 'lazobr27@bearsmail.org',         'directory_import'),
  ('tyler l|11',       'Tyler L',       'tyler l',       11, 'levittty@bearsmail.org',         'directory_import'),
  ('greg l|11',        'Greg L',        'greg l',        11, 'lisowskigr27@bearsmail.org',     'directory_import'),
  ('franklin l|11',    'Franklin L',    'franklin l',    11, 'loftusfr@bearsmail.org',         'directory_import'),
  ('braiden l|11',     'Braiden L',     'braiden l',     11, 'lynnbr@bearsmail.org',           'directory_import'),
  ('annabelle m|11',   'Annabelle M',   'annabelle m',   11, 'marshallan@bearsmail.org',       'directory_import'),
  ('preston m|11',     'Preston M',     'preston m',     11, 'massiepr27@bearsmail.org',       'directory_import'),
  ('maddie m|11',      'Maddie M',      'maddie m',      11, 'mcdonaldma@bearsmail.org',       'directory_import'),
  ('tommy m|11',       'Tommy M',       'tommy m',       11, 'mcleodto@bearsmail.org',         'directory_import'),
  ('collier m|11',     'Collier M',     'collier m',     11, 'mcmullenco@bearsmail.org',       'directory_import'),
  ('colt m|11',        'Colt M',        'colt m',        11, 'mcnamaraco27@bearsmail.org',     'directory_import'),
  ('dean m|11',        'Dean M',        'dean m',        11, 'mellonde27@bearsmail.org',       'directory_import'),
  ('havana m|11',      'Havana M',      'havana m',      11, 'miguelha@bearsmail.org',         'directory_import'),
  ('matthew m|11',     'Matthew M',     'matthew m',     11, 'mikitama27@bearsmail.org',       'directory_import'),
  ('kade m|11',        'Kade M',        'kade m',        11, 'minutaglioka27@bearsmail.org',   'directory_import'),
  ('griffin m|11',     'Griffin M',     'griffin m',     11, 'mooregr27@bearsmail.org',        'directory_import'),
  ('hayes m|11',       'Hayes M',       'hayes m',       11, 'morganha@bearsmail.org',         'directory_import'),
  ('mose m|11',        'Mose M',        'mose m',        11, 'murraymo@bearsmail.org',         'directory_import'),
  ('daniel n|11',      'Daniel N',      'daniel n',      11, 'neumannda@bearsmail.org',        'directory_import'),
  ('vandy n|11',       'Vandy N',       'vandy n',       11, 'neumeyerva27@bearsmail.org',     'directory_import'),
  ('logan n|11',       'Logan N',       'logan n',       11, 'newsomelo27@bearsmail.org',      'directory_import'),
  ('caroline n|11',    'Caroline N',    'caroline n',    11, 'newtonca27@bearsmail.org',       'directory_import'),
  ('scarlett p|11',    'Scarlett P',    'scarlett p',    11, 'paynesc@bearsmail.org',          'directory_import'),
  ('mcvey p|11',       'McVey P',       'mcvey p',       11, 'pedenmc@bearsmail.org',          'directory_import'),
  ('george p|11',      'George P',      'george p',      11, 'peelerge27@bearsmail.org',       'directory_import'),
  ('chloe p|11',       'Chloe P',       'chloe p',       11, 'piercech27@bearsmail.org',       'directory_import'),
  ('jack p|11',        'Jack P',        'jack p',        11, 'pileggija27@bearsmail.org',      'directory_import'),
  ('luke p|11',        'Luke P',        'luke p',        11, 'provostylu@bearsmail.org',       'directory_import'),
  ('caroline p|11',    'Caroline P',    'caroline p',    11, 'pruittca@bearsmail.org',         'directory_import'),
  ('layla r|11',       'Layla R',       'layla r',       11, 'ricciola@bearsmail.org',         'directory_import'),
  ('ryder r|11',       'Ryder R',       'ryder r',       11, 'rippsry@bearsmail.org',          'directory_import'),
  ('ray r|11',         'Ray R',         'ray r',         11, 'rookerra@bearsmail.org',         'directory_import'),
  ('victoria s|11',    'Victoria S',    'victoria s',    11, 'saigalvi27@bearsmail.org',       'directory_import'),
  ('mayomi s|11',      'Mayomi S',      'mayomi s',      11, 'sannima27@bearsmail.org',        'directory_import'),
  ('maya s|11',        'Maya S',        'maya s',        11, 'shahma27@bearsmail.org',         'directory_import'),
  ('sarah s|11',       'Sarah S',       'sarah s',       11, 'shrumsa27@bearsmail.org',        'directory_import'),
  ('luke s|11',        'Luke S',        'luke s',        11, 'shumatelu27@bearsmail.org',      'directory_import'),
  ('grace s|11',       'Grace S',       'grace s',       11, 'simpsongr@bearsmail.org',        'directory_import'),
  ('bobby s|11',       'Bobby S',       'bobby s',       11, 'skryneckibo@bearsmail.org',      'directory_import'),
  -- bryce s|11 → Shortt inserted; Smith (smithbr@bearsmail.org) must register manually
  ('bryce s|11',       'Bryce S',       'bryce s',       11, 'shorttbr@bearsmail.org',         'directory_import'),
  ('sienna s|11',      'Sienna S',      'sienna s',      11, 'shorttsi@bearsmail.org',         'directory_import'),
  ('charlie s|11',     'Charlie S',     'charlie s',     11, 'smithch27@bearsmail.org',        'directory_import'),
  ('lilah s|11',       'Lilah S',       'lilah s',       11, 'smithli27@bearsmail.org',        'directory_import'),
  ('sean s|11',        'Sean S',        'sean s',        11, 'smithse@bearsmail.org',          'directory_import'),
  ('kenzo s|11',       'Kenzo S',       'kenzo s',       11, 'sonodake27@bearsmail.org',       'directory_import'),
  ('leah s|11',        'Leah S',        'leah s',        11, 'stonele@bearsmail.org',          'directory_import'),
  ('jules s|11',       'Jules S',       'jules s',       11, 'sunkaraju@bearsmail.org',        'directory_import'),
  ('william t|11',     'William T',     'william t',     11, 'tablerwi@bearsmail.org',         'directory_import'),
  ('gabriella t|11',   'Gabriella T',   'gabriella t',   11, 'tavelga27@bearsmail.org',        'directory_import'),
  ('charlotte t|11',   'Charlotte T',   'charlotte t',   11, 'terrych27@bearsmail.org',        'directory_import'),
  ('sasha t|11',       'Sasha T',       'sasha t',       11, 'thompsonsa27@bearsmail.org',     'directory_import'),
  ('sophia t|11',      'Sophia T',      'sophia t',      11, 'toledoso@bearsmail.org',         'directory_import'),
  ('tanner v|11',      'Tanner V',      'tanner v',      11, 'vassianta27@bearsmail.org',      'directory_import'),
  ('marley v|11',      'Marley V',      'marley v',      11, 'vaughnma27@bearsmail.org',       'directory_import'),
  ('eva marie w|11',   'Eva Marie W',   'eva marie w',   11, 'wakelinev@bearsmail.org',        'directory_import'),
  ('brent w|11',       'Brent W',       'brent w',       11, 'warbingtonbr27@bearsmail.org',   'directory_import'),
  ('chase w|11',       'Chase W',       'chase w',       11, 'warbingtonch27@bearsmail.org',   'directory_import'),
  ('harley w|11',      'Harley W',      'harley w',      11, 'wardh@bearsmail.org',            'directory_import'),
  ('jack w|11',        'Jack W',        'jack w',        11, 'wardnerja@bearsmail.org',        'directory_import'),
  ('makayla w|11',     'Makayla W',     'makayla w',     11, 'weaverma27@bearsmail.org',       'directory_import'),
  ('grayson w|11',     'Grayson W',     'grayson w',     11, 'whittygr@bearsmail.org',         'directory_import'),
  ('claire w|11',      'Claire W',      'claire w',      11, 'wilhelmcl@bearsmail.org',        'directory_import'),
  ('christian w|11',   'Christian W',   'christian w',   11, 'williamsch27@bearsmail.org',     'directory_import'),
  ('munchie w|11',     'Munchie W',     'munchie w',     11, 'worthymu27@bearsmail.org',       'directory_import'),
  ('nicole x|11',      'Nicole X',      'nicole x',      11, 'xuni27@bearsmail.org',           'directory_import'),
  -- Jack U = Jack Underwood
  ('jack u|11',        'Jack Underwood','jack underwood',11, 'underwoodja@bearsmail.org',       'directory_import'),
  ('lily m|11',        'Lily M',        'lily m',        11, 'millerli27@bearsmail.org',       'directory_import')
ON CONFLICT (player_key) DO UPDATE SET
  microsoft_email = EXCLUDED.microsoft_email,
  updated_at      = now()
WHERE player_profiles.microsoft_email IS NULL;

-- ── Grade 12 — Class of 2026 ─────────────────────────────────────
INSERT INTO public.player_profiles
  (player_key, player_name, player_name_key, grade, microsoft_email, source)
VALUES
  ('chase a|12',        'Chase A',        'chase a',        12, 'anarumoch@bearsmail.org',        'directory_import'),
  ('rania b|12',        'Rania B',        'rania b',        12, 'bhatiara26@bearsmail.org',       'directory_import'),
  ('matthew b|12',      'Matthew B',      'matthew b',      12, 'binneyma@bearsmail.org',         'directory_import'),
  ('jb b|12',           'Jb B',           'jb b',           12, 'blountja26@bearsmail.org',       'directory_import'),
  ('brooks b|12',       'Brooks B',       'brooks b',       12, 'battlesonbr26@bearsmail.org',    'directory_import'),
  ('ryan b|12',         'Ryan B',         'ryan b',         12, 'beckry26@bearsmail.org',         'directory_import'),
  ('emma b|12',         'Emma B',         'emma b',         12, 'belle@bearsmail.org',            'directory_import'),
  ('henry b|12',        'Henry B',        'henry b',        12, 'brooshe@bearsmail.org',          'directory_import'),
  ('simone b|12',       'Simone B',       'simone b',       12, 'brunsonsi26@bearsmail.org',      'directory_import'),
  ('caitlyn b|12',      'Caitlyn B',      'caitlyn b',      12, 'burrisca@bearsmail.org',         'directory_import'),
  ('claire b|12',       'Claire B',       'claire b',       12, 'busbycl@bearsmail.org',          'directory_import'),
  ('catherine b|12',    'Catherine B',    'catherine b',    12, 'buschca@bearsmail.org',          'directory_import'),
  ('marshall c|12',     'Marshall C',     'marshall c',     12, 'campma@bearsmail.org',           'directory_import'),
  ('addie c|12',        'Addie C',        'addie c',        12, 'campbellad@bearsmail.org',       'directory_import'),
  ('andrew c|12',       'Andrew C',       'andrew c',       12, 'campbellan@bearsmail.org',       'directory_import'),
  ('sophie c|12',       'Sophie C',       'sophie c',       12, 'cardilloso26@bearsmail.org',     'directory_import'),
  ('james c|12',        'James C',        'james c',        12, 'carperja@bearsmail.org',         'directory_import'),
  ('blair c|12',        'Blair C',        'blair c',        12, 'claytonbl26@bearsmail.org',      'directory_import'),
  ('kennedy c|12',      'Kennedy C',      'kennedy c',      12, 'codyke26@bearsmail.org',         'directory_import'),
  ('alex c|12',         'Alex C',         'alex c',         12, 'coleyal@bearsmail.org',          'directory_import'),
  ('benjamin c|12',     'Benjamin C',     'benjamin c',     12, 'cookbe@bearsmail.org',           'directory_import'),
  ('gigi c|12',         'Gigi C',         'gigi c',         12, 'coregi@bearsmail.org',           'directory_import'),
  ('macon c|12',        'Macon C',        'macon c',        12, 'corem@bearsmail.org',            'directory_import'),
  ('ben c|12',          'Ben C',          'ben c',          12, 'corleybe@bearsmail.org',         'directory_import'),
  ('charlie c|12',      'Charlie C',      'charlie c',      12, 'cortsch@bearsmail.org',          'directory_import'),
  ('ollie c|12',        'Ollie C',        'ollie c',        12, 'courtsol@bearsmail.org',         'directory_import'),
  ('harper c|12',       'Harper C',       'harper c',       12, 'crandallha@bearsmail.org',       'directory_import'),
  ('callie c|12',       'Callie C',       'callie c',       12, 'creelca26@bearsmail.org',        'directory_import'),
  ('beckett c|12',      'Beckett C',      'beckett c',      12, 'culbertsonbe@bearsmail.org',     'directory_import'),
  ('vivian e|12',       'Vivian E',       'vivian e',       12, 'earlyvi@bearsmail.org',          'directory_import'),
  ('maya e|12',         'Maya E',         'maya e',         12, 'eckartma26@bearsmail.org',       'directory_import'),
  ('gavin e|12',        'Gavin E',        'gavin e',        12, 'evansg@bearsmail.org',           'directory_import'),
  ('henry f|12',        'Henry F',        'henry f',        12, 'fahyhe@bearsmail.org',           'directory_import'),
  ('sarah f|12',        'Sarah F',        'sarah f',        12, 'fishmansa@bearsmail.org',        'directory_import'),
  ('mac f|12',          'Mac F',          'mac f',          12, 'flinnma@bearsmail.org',          'directory_import'),
  ('taylor f|12',       'Taylor F',       'taylor f',       12, 'fullerta@bearsmail.org',         'directory_import'),
  ('ethan g|12',        'Ethan G',        'ethan g',        12, 'ganucheauet26@bearsmail.org',    'directory_import'),
  ('kate g|12',         'Kate G',         'kate g',         12, 'georgeka26@bearsmail.org',       'directory_import'),
  ('ella g|12',         'Ella G',         'ella g',         12, 'ghirardiel26@bearsmail.org',     'directory_import'),
  ('peyton g|12',       'Peyton G',       'peyton g',       12, 'gluesingpe@bearsmail.org',       'directory_import'),
  ('cooper g|12',       'Cooper G',       'cooper g',       12, 'gravesco@bearsmail.org',         'directory_import'),
  ('jack g|12',         'Jack G',         'jack g',         12, 'grahamja@bearsmail.org',         'directory_import'),
  ('grant h|12',        'Grant H',        'grant h',        12, 'heeringr@bearsmail.org',         'directory_import'),
  ('john h|12',         'John H',         'john h',         12, 'hennjo@bearsmail.org',           'directory_import'),
  ('hannah h|12',       'Hannah H',       'hannah h',       12, 'hermanh@bearsmail.org',          'directory_import'),
  ('hazel h|12',        'Hazel H',        'hazel h',        12, 'hewettha@bearsmail.org',         'directory_import'),
  ('claire h|12',       'Claire H',       'claire h',       12, 'hobbscl26@bearsmail.org',        'directory_import'),
  ('gabe h|12',         'Gabe H',         'gabe h',         12, 'hoffenbergga26@bearsmail.org',   'directory_import'),
  ('brooke h|12',       'Brooke H',       'brooke h',       12, 'hausmannbr@bearsmail.org',       'directory_import'),
  ('lily h|12',         'Lily H',         'lily h',         12, 'hudsonli@bearsmail.org',         'directory_import'),
  ('brady h|12',        'Brady H',        'brady h',        12, 'hueskenbr@bearsmail.org',        'directory_import'),
  ('jake h|12',         'Jake H',         'jake h',         12, 'hunterja@bearsmail.org',         'directory_import'),
  ('devin h|12',        'Devin H',        'devin h',        12, 'hutchersonde26@bearsmail.org',   'directory_import'),
  ('sam h|12',          'Sam H',          'sam h',          12, 'huttosa@bearsmail.org',          'directory_import'),
  ('myles j|12',        'Myles J',        'myles j',        12, 'jacksonmy@bearsmail.org',        'directory_import'),
  ('carson j|12',       'Carson J',       'carson j',       12, 'jamesca@bearsmail.org',          'directory_import'),
  ('sophia j|12',       'Sophia J',       'sophia j',       12, 'jarboeso@bearsmail.org',         'directory_import'),
  ('jameson k|12',      'Jameson K',      'jameson k',      12, 'kardianja@bearsmail.org',        'directory_import'),
  ('fallon k|12',       'Fallon K',       'fallon k',       12, 'kaufmanfa@bearsmail.org',        'directory_import'),
  ('baxter k|12',       'Baxter K',       'baxter k',       12, 'kelleyba@bearsmail.org',         'directory_import'),
  ('romina k|12',       'Romina K',       'romina k',       12, 'khademiro@bearsmail.org',        'directory_import'),
  ('simran k|12',       'Simran K',       'simran k',       12, 'khannasi@bearsmail.org',         'directory_import'),
  ('bailey k|12',       'Bailey K',       'bailey k',       12, 'kloberdanzba@bearsmail.org',     'directory_import'),
  ('james l|12',        'James L',        'james l',        12, 'labruyereja26@bearsmail.org',    'directory_import'),
  ('mary frances l|12', 'Mary Frances L', 'mary frances l', 12, 'laceyma@bearsmail.org',          'directory_import'),
  ('stefano l|12',      'Stefano L',      'stefano l',      12, 'laiosst@bearsmail.org',          'directory_import'),
  ('samuel l|12',       'Samuel L',       'samuel l',       12, 'lambacksa@bearsmail.org',        'directory_import'),
  ('dorothy l|12',      'Dorothy L',      'dorothy l',      12, 'landerdo@bearsmail.org',         'directory_import'),
  ('maddie l|12',       'Maddie L',       'maddie l',       12, 'lawrencema@bearsmail.org',       'directory_import'),
  ('grace l|12',        'Grace L',        'grace l',        12, 'leonardgr@bearsmail.org',        'directory_import'),
  ('julie l|12',        'Julie L',        'julie l',        12, 'luttrellju26@bearsmail.org',      'directory_import'),
  ('wyatt m|12',        'Wyatt M',        'wyatt m',        12, 'maiellarowy@bearsmail.org',      'directory_import'),
  ('lila m|12',         'Lila M',         'lila m',         12, 'massanellili@bearsmail.org',     'directory_import'),
  ('kayden m|12',       'Kayden M',       'kayden m',       12, 'massihka@bearsmail.org',         'directory_import'),
  ('patrick m|12',      'Patrick M',      'patrick m',      12, 'mathispa@bearsmail.org',         'directory_import'),
  ('jordan m|12',       'Jordan M',       'jordan m',       12, 'maysjo@bearsmail.org',           'directory_import'),
  ('parker m|12',       'Parker M',       'parker m',       12, 'mccallumpa26@bearsmail.org',     'directory_import'),
  ('nicholas m|12',     'Nicholas M',     'nicholas m',     12, 'mckayni@bearsmail.org',          'directory_import'),
  ('jay m|12',          'Jay M',          'jay m',          12, 'mckownja@bearsmail.org',         'directory_import'),
  ('elana m|12',        'Elana M',        'elana m',        12, 'mcmastersel26@bearsmail.org',    'directory_import'),
  ('graham m|12',       'Graham M',       'graham m',       12, 'mcnultygr@bearsmail.org',        'directory_import'),
  ('ethan m|12',        'Ethan M',        'ethan m',        12, 'meisingeret@bearsmail.org',      'directory_import'),
  ('gavin m|12',        'Gavin M',        'gavin m',        12, 'milesga@bearsmail.org',          'directory_import'),
  ('thomas m|12',       'Thomas M',       'thomas m',       12, 'millerth@bearsmail.org',         'directory_import'),
  ('kate m|12',         'Kate M',         'kate m',         12, 'mirgorodka@bearsmail.org',       'directory_import'),
  ('andrew m|12',       'Andrew M',       'andrew m',       12, 'moorean26@bearsmail.org',        'directory_import'),
  ('caroline m|12',     'Caroline M',     'caroline m',     12, 'morganca26@bearsmail.org',       'directory_import'),
  ('madison m|12',      'Madison M',      'madison m',      12, 'murrayma@bearsmail.org',         'directory_import'),
  ('matthew n|12',      'Matthew N',      'matthew n',      12, 'neumannma@bearsmail.org',        'directory_import'),
  ('nate n|12',         'Nate N',         'nate n',         12, 'newsomena26@bearsmail.org',      'directory_import'),
  ('haylen n|12',       'Haylen N',       'haylen n',       12, 'nicholsha26@bearsmail.org',      'directory_import'),
  ('mary kathryn n|12', 'Mary Kathryn N', 'mary kathryn n', 12, 'noblema@bearsmail.org',          'directory_import'),
  ('charlie n|12',      'Charlie N',      'charlie n',      12, 'northcuttch@bearsmail.org',      'directory_import'),
  ('sophia o|12',       'Sophia O',       'sophia o',       12, 'ocamposo26@bearsmail.org',       'directory_import'),
  ('marcos p|12',       'Marcos P',       'marcos p',       12, 'pachecoma26@bearsmail.org',      'directory_import'),
  ('sairis p|12',       'Sairis P',       'sairis p',       12, 'panahsa@bearsmail.org',          'directory_import'),
  ('alexa p|12',        'Alexa P',        'alexa p',        12, 'pattonal@bearsmail.org',         'directory_import'),
  ('dawson r|12',       'Dawson R',       'dawson r',       12, 'radaszewskida@bearsmail.org',    'directory_import'),
  ('spencer r|12',      'Spencer R',      'spencer r',      12, 'reedsp@bearsmail.org',           'directory_import'),
  ('jada r|12',         'Jada R',         'jada r',         12, 'reevesja26@bearsmail.org',       'directory_import'),
  ('margaret r|12',     'Margaret R',     'margaret r',     12, 'reynoldsma@bearsmail.org',       'directory_import'),
  ('reese r|12',        'Reese R',        'reese r',        12, 'robertsre@bearsmail.org',        'directory_import'),
  ('olivia r|12',       'Olivia R',       'olivia r',       12, 'ruinenol26@bearsmail.org',       'directory_import'),
  ('julia r|12',        'Julia R',        'julia r',        12, 'russellju@bearsmail.org',        'directory_import'),
  ('katherine s|12',    'Katherine S',    'katherine s',    12, 'shannonka@bearsmail.org',        'directory_import'),
  ('keval s|12',        'Keval S',        'keval s',        12, 'shethke@bearsmail.org',          'directory_import'),
  ('sophia s|12',       'Sophia S',       'sophia s',       12, 'siddiquiso@bearsmail.org',       'directory_import'),
  ('jordynn s|12',      'Jordynn S',      'jordynn s',      12, 'skinnerjo@bearsmail.org',        'directory_import'),
  ('lewis s|12',        'Lewis S',        'lewis s',        12, 'smithle@bearsmail.org',          'directory_import'),
  ('skylar s|12',       'Skylar S',       'skylar s',       12, 'smithsk@bearsmail.org',          'directory_import'),
  ('tommy s|12',        'Tommy S',        'tommy s',        12, 'smithto@bearsmail.org',          'directory_import'),
  ('steele s|12',       'Steele S',       'steele s',       12, 'southerlandst@bearsmail.org',   'directory_import'),
  ('brooke s|12',       'Brooke S',       'brooke s',       12, 'sprayberrybr@bearsmail.org',    'directory_import'),
  ('denim s|12',        'Denim S',        'denim s',        12, 'stevensde26@bearsmail.org',      'directory_import'),
  ('olivia s|12',       'Olivia S',       'olivia s',       12, 'stiversol@bearsmail.org',        'directory_import'),
  ('dallas s|12',       'Dallas S',       'dallas s',       12, 'stricklandda@bearsmail.org',     'directory_import'),
  ('austin s|12',       'Austin S',       'austin s',       12, 'strobridgeau@bearsmail.org',     'directory_import'),
  ('lilly s|12',        'Lilly S',        'lilly s',        12, 'studleyli@bearsmail.org',        'directory_import'),
  ('sullivan s|12',     'Sullivan S',     'sullivan s',     12, 'swannsu@bearsmail.org',          'directory_import'),
  ('alex t|12',         'Alex T',         'alex t',         12, 'talbertal@bearsmail.org',        'directory_import'),
  ('hollis t|12',       'Hollis T',       'hollis t',       12, 'thompsonho@bearsmail.org',       'directory_import'),
  ('zion t|12',         'Zion T',         'zion t',         12, 'tilliszi26@bearsmail.org',       'directory_import'),
  ('rio t|12',          'Rio T',          'rio t',          12, 'tomosunasri26@bearsmail.org',    'directory_import'),
  ('blake t|12',        'Blake T',        'blake t',        12, 'towsonbl26@bearsmail.org',       'directory_import'),
  ('caroline t|12',     'Caroline T',     'caroline t',     12, 'tuckerca@bearsmail.org',         'directory_import'),
  ('elena u|12',        'Elena U',        'elena u',        12, 'utzel@bearsmail.org',            'directory_import'),
  ('jack v|12',         'Jack V',         'jack v',         12, 'vetteseja@bearsmail.org',        'directory_import'),
  ('will v|12',         'Will V',         'will v',         12, 'vinciwi26@bearsmail.org',        'directory_import'),
  ('tate v|12',         'Tate V',         'tate v',         12, 'voigtta26@bearsmail.org',        'directory_import'),
  ('evan w|12',         'Evan W',         'evan w',         12, 'wandtkeev@bearsmail.org',        'directory_import'),
  ('cate w|12',         'Cate W',         'cate w',         12, 'wassenaarca@bearsmail.org',      'directory_import'),
  ('bradlee w|12',      'Bradlee W',      'bradlee w',      12, 'williamsbr26@bearsmail.org',     'directory_import'),
  ('xavier w|12',       'Xavier W',       'xavier w',       12, 'wilsonxa26@bearsmail.org',       'directory_import'),
  ('miller w|12',       'Miller W',       'miller w',       12, 'wimberlymi26@bearsmail.org',     'directory_import'),
  ('anna w|12',         'Anna W',         'anna w',         12, 'windleyan@bearsmail.org',        'directory_import'),
  ('fletcher w|12',     'Fletcher W',     'fletcher w',     12, 'witzigreuterfl@bearsmail.org',  'directory_import'),
  ('henry w|12',        'Henry W',        'henry w',        12, 'woodhe@bearsmail.org',           'directory_import'),
  ('khalid w|12',       'Khalid W',       'khalid w',       12, 'worthykh26@bearsmail.org',       'directory_import')
ON CONFLICT (player_key) DO UPDATE SET
  microsoft_email = EXCLUDED.microsoft_email,
  updated_at      = now()
WHERE player_profiles.microsoft_email IS NULL;
