name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: npm install
      - name: Normalize formatting
        run: npm run fix
      - name: Check formatting
        run: npm run lint
