name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npm install
      - name: Run tests in CI mode
        run: CI=true npm test -- --watch=false
